### ISSUE TITLE
bug: nil pointer exception in workload-projector

### ISSUE THREAD

**Issue by clubanderson** [kubestellar/kubestellar#1076]
### Describe the bug

workload-projector line 1006 (logger.error) is throwing nil pointer exception

in v0.7.0

### Steps To Reproduce

1. run kubestellar

### Expected Behavior

no exceptions please

### Additional Context

from Mike Spreitzer (internal) to Everyone:    2:44  PM
kubectl get Workspace -o "custom-columns=NAME:.metadata.name,SYNCTARGET:.metadata.annotations['edge\.kubestellar\.io/sync-target-name'],CLUSTER:.spec.cluster"
from Andy Anderson (internal) to Everyone:    2:56  PM
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1907ea6]
goroutine 1000 [running]:
k8s.io/apimachinery/pkg/apis/meta/v1/unstructured.(*Unstructured).GetResourceVersion(...)
	/Users/andan02/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apimachinery@v0.0.0-20230210192259-aaa28aa88b2d/pkg/apis/meta/v1/unstructured/unstructured.go:282
github.com/kubestellar/kubestellar/pkg/placement.(*workloadProjector).syncSourceToDestLocked.func1()
	/Users/andan02/projects/main/kubestellar/pkg/placement/workload-projector.go:1006 +0x8a6
github.com/kubestellar/kubestellar/pkg/placement.(*workloadProjector).syncSourceObject(0x10?, {0x251e078, 0xc000adbc80}, {{0xc001642ed0, 0x10}, {{0x0, 0x0}, {0xc0040b0740, 0xa}}, {0xc004de06d0, ...}, ...})
	/Users/andan02/projects/main/kubestellar/pkg/placement/workload-projector.go:915 +0x21b
github.com/kubestellar/kubestellar/pkg/placement.(*workloadProjector).sync1Conf

**Comment by clubanderson** [comment]
[pt.txt.zip](https://github.com/kubestellar/kubestellar/files/12796095/pt.txt.zip)

**Comment by clubanderson** [comment]
#1080 is a dupe - closed #1080 for now

**Comment by clubanderson** [comment]
This is fixed. Requires testing.

**Comment by clubanderson** [comment]
appears to be fixed - Thank you
