### ISSUE TITLE
bug: concurrency bug wrt kube-bind - space name relationship

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#1452]
### Describe the bug

The `kubestellar-kube-bind` script writes the ConfigMap that holds the relationship _after_ doing the `kubectl bind` operation, so projected objects can arrive in the KCS before the ConfigMap.  The mailbox controller has an `IndexFunc` that returns an error if it can not follow the relationship. Did you know that returning an error from an `IndexFunc` causes a panic? Following is an excerpt from a mailbox controller log.

```
...
I1211 12:33:27.365162   93943 reflector.go:271] Starting reflector *v2alpha1.SyncTarget (0s) from k8s.io/client-go@v0.0.0-20230210192259-aaa28aa88b2d/tools/cache/reflector.go:215
I1211 12:33:27.365176   93943 reflector.go:307] Listing and watching *v2alpha1.SyncTarget from k8s.io/client-go@v0.0.0-20230210192259-aaa28aa88b2d/tools/cache/reflector.go:215
I1211 12:33:27.365182   93943 reflector.go:271] Starting reflector *v1alpha1.Space (0s) from k8s.io/client-go@v0.0.0-20230210192259-aaa28aa88b2d/tools/cache/reflector.go:215
I1211 12:33:27.365190   93943 reflector.go:307] Listing and watching *v1alpha1.Space from k8s.io/client-go@v0.0.0-20230210192259-aaa28aa88b2d/tools/cache/reflector.go:215
E1211 12:33:27.366187   93943 controller.go:382] "failed to get consumer space ID from a provider's copy" err="failed to retrive spaceID" syncTarget="kube-bind-4hzzv-florin"
E1211 12:33:27.366324   93943 runtime.go:79] Observed a panic: &errors.errorString{s:"unable to calculate an index entry for key \"kube-bind-4hzzv-florin\" on index \"mbsName\": failed to retrive spaceID"} (unable to calculate an index entry for key "kube-bind-4hzzv-florin" on index "mbsName": failed to retrive spaceID)
goroutine 104 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x106414ce0?, 0x140003e1c00})
	/Users/mspreitz/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apimachinery@v0.0.0-20230210192259-aaa28aa88b2d/pkg/util/runtime/runtime.go:75 +0x7c
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x140006aab10?})
	/Users/mspreitz/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apimachinery@v0.0.0-20230210192259-aaa28aa88b2d/pkg/util/runtime/runtime.go:49 +0x78
panic({0x106414ce0, 0x140003e1c00})
	/opt/homebrew/Cellar/go@1.19/1.19.13/libexec/src/runtime/panic.go:884 +0x204
k8s.io/client-go/tools/cache.(*threadSafeMap).updateIndices(0x140006aab10, {0x0, 0x0}, {0x10664b4e0?, 0x1400073ce00}, {0x140000449c0, 0x16})
	/Users/mspreitz/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/client-go@v0.0.0-20230210192259-aaa28aa88b2d/tools/cache/thread_safe_store.go:274 +0x4e0
k8s.io/client-go/tools/cache.(*threadSafeMap).Update(0x140006aab10, {0x140000449c0, 0x16}, {0x10664b4e0?, 0x1400073ce00})
	/Users/mspreitz/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/client-go@v0.0.0-20230210192259-aaa28aa88b2d/tools/cache/thread_safe_store.go:82 +0x108
k8s.io/client-go/tools/cache.(*threadSafeMap).Add(0x10664b4e0?, {0x140000449c0?, 0x10664b4e0?}, {0x10664b4e0?, 0x1400073ce00?})
	/Users/mspreitz/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/client-go@v0.0.0-20230210192259-aaa28aa88b2d/tools/cache/thread_safe_store.go:74 +0x28
...
```

### Steps To Reproduce

Not sure

### Expected Behavior

The controller does not panic when allowed things happen.

**Comment by MikeSpreitzer** [comment]
Fixed in #1453
