### ISSUE TITLE
bug: controller-gen redux

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#1917]
### Describe the bug

`make manifests` fails when controller-gen is built using Go version 1.22. The following typescript shows the failure, and ends with showing the versions involved.

```shell
 mspreitz@mjs13 kubestellar % rm bin/*
zsh: sure you want to delete the only file in /Users/mspreitz/go/src/github.com/kubestellar/kubestellar/bin [yn]? y

mspreitz@mjs13 kubestellar % make manifests
test -s /Users/mspreitz/go/src/github.com/kubestellar/kubestellar/bin/controller-gen && /Users/mspreitz/go/src/github.com/kubestellar/kubestellar/bin/controller-gen --version | grep -q v0.11.3 || \
	GOBIN=/Users/mspreitz/go/src/github.com/kubestellar/kubestellar/bin go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.11.3
/Users/mspreitz/go/src/github.com/kubestellar/kubestellar/bin/controller-gen rbac:roleName=manager-role crd webhook paths="./api/..." output:crd:artifacts:config=config/crd/bases
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x103154084]

goroutine 85 [running]:
go/types.(*Checker).handleBailout(0x1400161c400, 0x140016f3d18)
	/opt/homebrew/Cellar/go/1.22.1/libexec/src/go/types/check.go:367 +0x9c
panic({0x10342d380?, 0x1039c7e90?})
	/opt/homebrew/Cellar/go/1.22.1/libexec/src/runtime/panic.go:770 +0x124
go/types.(*StdSizes).Sizeof(0x0, {0x1034f7cb0, 0x1039d0640})
	/opt/homebrew/Cellar/go/1.22.1/libexec/src/go/types/sizes.go:228 +0x314
go/types.(*Config).sizeof(...)
	/opt/homebrew/Cellar/go/1.22.1/libexec/src/go/types/sizes.go:333
go/types.representableConst.func1({0x1034f7cb0?, 0x1039d0640?})
	/opt/homebrew/Cellar/go/1.22.1/libexec/src/go/types/const.go:76 +0x9c
go/types.representableConst({0x1034fdef0, 0x10399c7c0}, 0x1400161c400, 0x1039d0640, 0x140016f3468)
	/opt/homebrew/Cellar/go/1.22.1/libexec/src/go/types/const.go:92 +0x138
go/types.(*Checker).representation(0x1400161c400, 0x140016e97c0, 0x1039d0640)
	/opt/homebrew/Cellar/go/1.22.1/libexec/src/go/types/const.go:256 +0x68
go/types.(*Checker).implicitTypeAndValue(0x1400161c400, 0x140016e97c0, {0x1034f7cd8, 0x14000106850})
	/opt/homebrew/Cellar/go/1.22.1/libexec/src/go/types/expr.go:375 +0x304
go/types.(*Checker).assignment(0x1400161c400, 0x140016e97c0, {0x1034f7cd8, 0x14000106850}, {0x10326d1a5, 0x14})
	/opt/homebrew/Cellar/go/1.22.1/libexec/src/go/types/assignments.go:52 +0x23c
go/types.(*Checker).initConst(0x1400161c400, 0x14001851b60, 0x140016e97c0)
	/opt/homebrew/Cellar/go/1.22.1/libexec/src/go/types/assignments.go:126 +0x274
go/types.(*Checker).constDecl(0x1400161c400, 0x14001851b60, {0x1034fa880, 0x14001224160}, {0x1034fa880, 0x14001224180}, 0x0)
	/opt/homebrew/Cellar/go/1.22.1/libexec/src/go/types/decl.go:490 +0x250
go/types.(*Checker).objDecl(0x1400161c400, {0x103503040, 0x14001851b60}, 0x0)
	/opt/homebrew/Cellar/go/1.22.1/libexec/src/go/types/decl.go:191 +0x84c
go/types.(*Checker).packageObjects(0x1400161c400)
	/opt/homebrew/Cellar/go/1.22.1/libexec/src/go/types/resolver.go:693 +0x468
go/types.(*Checker).checkFiles(0x1400161c400, {0x14000fe75f0, 0x5, 0x5})
	/opt/homebrew/Cellar/go/1.22.1/libexec/src/go/types/check.go:408 +0x164
go/types.(*Checker).Files(...)
	/opt/homebrew/Cellar/go/1.22.1/libexec/src/go/types/check.go:372
sigs.k8s.io/controller-tools/pkg/loader.(*loader).typeCheck(0x140002ff140, 0x140002523a0)
	/Users/mspreitz/go/pkg/mod/sigs.k8s.io/controller-tools@v0.11.3/pkg/loader/loader.go:286 +0x2d8
sigs.k8s.io/controller-tools/pkg/loader.(*Package).NeedTypesInfo(0x140002523a0)
	/Users/mspreitz/go/pkg/mod/sigs.k8s.io/controller-tools@v0.11.3/pkg/loader/loader.go:99 +0x44
sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check(0x14000259830, 0x140002523a0)
	/Users/mspreitz/go/pkg/mod/sigs.k8s.io/controller-tools@v0.11.3/pkg/loader/refs.go:268 +0x304
sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check.func1(0x42?)
	/Users/mspreitz/go/pkg/mod/sigs.k8s.io/controller-tools@v0.11.3/pkg/loader/refs.go:262 +0x58
created by sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check in goroutine 13
	/Users/mspreitz/go/pkg/mod/sigs.k8s.io/controller-tools@v0.11.3/pkg/loader/refs.go:260 +0x230
make: *** [manifests] Error 2

mspreitz@mjs13 kubestellar % go version
go version go1.22.1 darwin/arm64

mspreitz@mjs13 kubestellar % git status
On branch main
Your branch is up to date with 'upstream/main'.

nothing to commit, working tree clean

mspreitz@mjs13 kubestellar % git rev-parse HEAD
5fb21f86d8e9886793f1d27e0e54c5dd96572d44
```

In contrast, I can continue as follows.

```shell
mspreitz@mjs13 kubestellar % rm bin/*
zsh: sure you want to delete the only file in /Users/mspreitz/go/src/github.com/kubestellar/kubestellar/bin [yn]? y

mspreitz@mjs13 kubestellar % source ~/bin/use-keg.sh Go@1.21
Added /opt/homebrew/Cellar/Go@1.21/1.21.8/bin
Added /opt/homebrew/Cellar/Go@1.21/1.21.8/libexec/bin

mspreitz@mjs13 kubestellar % make manifests
test -s /Users/mspreitz/go/src/github.com/kubestellar/kubestellar/bin/controller-gen && /Users/mspreitz/go/src/github.com/kubestellar/kubestellar/bin/controller-gen --version | grep -q v0.11.3 || \
	GOBIN=/Users/mspreitz/go/src/github.com/kubestellar/kubestellar/bin go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.11.3
/Users/mspreitz/go/src/github.com/kubestellar/kubestellar/bin/controller-gen rbac:roleName=manager-role crd webhook paths="./api/..." output:crd:artifacts:config=config/crd/bases
cp config/crd/bases/* pkg/crd/files
```

### Steps To Reproduce

See above

### Expected Behavior

Our make targets succeed even with the latest version of Go.

### Additional Context

Remember that our Makefile calls for a specific version of controller-gen.

**Comment by MikeSpreitzer** [comment]
Sadly, version 0.13.0 of controller-tools also fails with go 1.22.1. Version 0.14.0 of controller-tools works with go 1.22.1, but has some sort of dependency on Kubernetes release 1.29.
